name: Lint

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 26
          cache: pnpm

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Run linters
        run: pnpm run lint
