name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: "26"
          package-manager-cache: false
      - run: npm ci
      - run: npm run build --if-present

      # Publish to NPM
      - uses: actions/setup-node@v7
        with:
          node-version: "26"
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --provenance --access public

      # Publish to GitHub
      - uses: actions/setup-node@v7
        with:
          node-version: "26"
          registry-url: "https://npm.pkg.github.com"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
